# Generated by Django 4.1.1 on 2022-10-09 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0003_alter_buslist_id_alter_reservation_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('bus', 'price')},
        ),
    ]
