# Generated by Django 4.1.1 on 2022-10-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0005_buslist_price_delete_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('cancel', 'cancel')], default='booked', max_length=20),
        ),
    ]
